baseURL = 'https://jmeagher.net/'
languageCode = 'en-us'
title = 'John Meagher'
googleAnalytics = "G-WQ4T6XKQJQ"

theme = 'beautifulhugo'


[params]
  sitename = "John Meagher's Ramblings"
  mainSections = ["old-blog-posts", "posts"]
  disableWebFonts = false
  Description = "John Meagher's Random Thoughts"
  dateFormat = "January 2006"
  hideAuthor = true
  logo = "images/HeadshotSquare.jpg"
  favicon = "images/favicon.png"
  author.name = "John Meagher"

[[menu.main]]
    name = "About Me"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Hire Me"
    url  = "/resume"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

[Author]
  github = "jmeagher"
  mastodon = "macaw.social/@jmeagher"
  linkedin = "jpmeagher"
  twitter = "john_meagher"
  facebook = "jmeagher"
