baseURL = 'https://jmeagher.net/'
languageCode = 'en-us'
title = 'John Meagher Home Site'
author = 'John Meagher'
theme = 'black-and-light'
googleAnalytics = "G-WQ4T6XKQJQ"


[params]
  sitename = "John Meagher's Ramblings"
  disableWebFonts = false
  Description = "John Meagher's random thoughts"

[[menu.main]]
    name = "About"
    url  = "/about"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/jmeagher"

